# tasks file for ssh_keygen
#- name: Copy key
  #src: ./Automationkey.pem
    #dest: /home/ansible/Automationkey.pem
    #owner: ansible
    #group: ansible

- name: Create an SSH key for "{{user_name}}"
  ansible.builtin.user:
    name: "{{user_name}}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa.pub

- name: Sync Pull task - Executed on  the Destination host "{{host2}}"
  #hosts: "{{host1}}"
  become_user: "{{user_name}}"  
  synchronize:
        src: /home/{{user_name}}/.ssh/id_rsa.pub
        dest: /home/{{user_name}}/.ssh/id_rsa.pub
        mode: pull
  delegate_to: "{{host2}}"
  register: syncfile
  run_once: true
  with_items:
       - .ssh/id_rsa.pub

#- name: Fetch ssh key for "{{user_name}}"
 # run_once: yes
 # fetch:
  #  src: /home/{{user_name}}/.ssh/id_rsa.pub
  #  dest: /tmp/
   # flat: yes

#- hosts: "{{item}}" 
 # copy:
  #  src: /tmp/id_rsa.pub
  #  dest: /home/{{user_name}}/.ssh/id_rsa.pub
      # when: "{{inventory_hostname == '{{host2}}'}}"
    #with_items:
   #   - "{{host2}}"
   #- name:  